name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.34.0-alpine

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: apk add --no-cache libjpeg-turbo-dev libpng-dev tiff-dev rsync
    - name: Build shards libraries
      run: make
    - name: Test
      run: crystal spec
    - name: Test static build
      run: crystal build --static --release src/image_size.cr
    - name: Generate docs
      run: crystal docs
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: true
